version: '3.8'

services:
  app:
    image: puhelinluettelo_frontend
    build:
      context: ./puhelinluettelo_frontend # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./puhelinluettelo_frontend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000

  server:
    image: puhelinluettelo_backend
    build:
      context: ./puhelinluettelo_backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./puhelinluettelo_backend:/usr/src/app
    ports:
      - 3001:3001

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-puhelinluettelo
    depends_on:
      - app
      - server
